server:
  port: 9001
eureka:
  instance:
    hostname: localhost
    appname: user
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://euk1.local:7001/eureka
spring:
  application:
    name: user