server:
  port: 7001

eureka:
  instance:
    hostname: localhost
    appname: localhost-eureka-7001
  client:
    # 不向注册中心注册自己
    register-with-eureka: false
    # 是否同步信息 , 单节点无需同步 ,  集群必须为true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka