server:
  port: 7001
eureka:
  instance:
    hostname: euk1.local
    appname: EurekaServer
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://euk2.local:7002/eureka/,http://euk1.local:7001/eureka/