spring:
  application:
    name: user
  zipkin:
    base-url: http://localhost:9411/
eureka:
  instance:
    hostname: localhost
    appname: user
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://euk1.local:7001/eureka,http://euk1.local:7002/eureka,http://euk1.local:7003/eureka
---
server:
  port: 9001
spring:
  profiles: node1
---
server:
  port: 9002
spring:
  profiles: node2
---
server:
  port: 9003
spring:
  profiles: node3