server:
  port: 4455
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CanonNr/SpringCloudConfigDemo #配置文件所在仓库
          default-label: master #配置文件分支
          #search-paths: config  #配置文件所在根目录
eureka:
  instance:
    hostname: localhost
    appname: config
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://euk1.local:7001/eureka,http://euk1.local:7002/eureka,http://euk1.local:7003/eureka